db-uri = "postgres://authenticator:texacore-local-super-secret@127.0.0.1:54322/postgres"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "texacore-jwt-secret-at-least-32-characters-long"
server-port = 3000
server-host = "127.0.0.1"
db-use-legacy-gucs = false
app-settings.jwt_secret = "texacore-jwt-secret-at-least-32-characters-long"
